// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image10":
            case "ball":return img`
. . 8 1 1 . . 
. f 8 1 1 f . 
1 1 f 1 f 2 2 
f f f f f f f 
2 2 f 1 f 1 1 
. f 1 1 8 f . 
. . 1 1 8 . . 
`;
            case "image4":
            case "wham":return img`
. . f f f f f . . 
. . 2 2 2 2 2 2 . 
. f f f f f f f . 
. f f f a f a f . 
. f f a a a a a . 
. . f a a a a a . 
. . . . a f f . . 
. a a 1 a a 1 a . 
a a a 1 f f 1 a a 
a a 1 f f f f 1 a 
a a f f 1 2 f f a 
a a f f 8 1 f f a 
a a f f f f f f a 
a a f f f f f f a 
a a 1 1 1 1 1 1 a 
a a f f f 8 f f a 
a a f f f 8 f f a 
. . f f f 8 f f . 
. . a a . . a a . 
. . a a . . a a . 
. . a a . . a a . 
. . 2 1 . . 2 1 . 
. . 1 1 1 . 1 1 1 
`;
            case "image6":
            case "tnt":return img`
. . . . f f f f f . . 
. . f f f f f e e f . 
. f f . f f e e e e . 
. f f . f e e f e f . 
. f f . f e e e e e . 
. f f . . e e e e e . 
f f . . . . e e e . . 
. . . e e 1 e e 1 e . 
. . e e e 1 f f 1 e e 
. . e e 1 f f f f 1 e 
. . e e f f 1 2 f f e 
. . e e f f 8 1 f f e 
. . e e f f f f f f e 
. . e e f f f f f f e 
. . e e 1 1 1 1 1 1 e 
. . e e f f f 8 f f e 
. . e e f f f 8 f f e 
. . . . f f f 8 f f . 
. . . . e e . . e e . 
. . . . e e . . e e . 
. . . . e e . . e e . 
. . . . 2 1 . . 2 1 . 
. . . . 1 1 1 . 1 1 1 
`;
            case "image7":
            case "jet":return img`
. . . f f f f . . 
. . f f f f f f . 
. . 1 1 1 1 1 1 . 
. . e e e e e e . 
. . e e e f e f . 
. . e e e e e e . 
. . . e e e e e . 
. . . . e e e . . 
. e e 1 e e 1 e . 
e e e 1 f f 1 e e 
e e 1 f f f f 1 e 
e e f f 1 2 f f e 
e e f f 8 1 f f e 
e e f f f f f f e 
e e f f f f f f e 
e e 1 1 1 1 1 1 e 
e e f f f 8 f f e 
e e f f f 8 f f e 
. . f f f 8 f f . 
. . e e . . e e . 
. . e e . . e e . 
. . e e . . e e . 
. . 2 1 . . 2 1 . 
. . 1 1 1 . 1 1 1 
`;
            case "image9":
            case "coach":return img`
. . . f f f f f . . . 
. . f f e e e f f . . 
. . f e e e e e f . . 
. . e e f e f e e . . 
. . e e e e e e e . . 
. . e f e e e f e . . 
. . . e f f f e . . . 
. . . . e e e . . . . 
. c c f 1 e 1 f c c . 
c c c f 1 2 1 f c c c 
c c c c f 2 f c c c c 
c c c c c f c c c c c 
c c c c c f c 1 1 c c 
c c c c c f c c c c c 
c c c c c f c c c c c 
1 1 c c f c f c c 1 1 
e e f f c c c f f e e 
e e c c c . c c c e e 
. . c c c . c c c . . 
. . c c c . c c c . . 
. . c c c . c c c . . 
. . f f f . f f f . . 
. . f f f . f f f . . 
`;
            case "image2":
            case "cheese":return img`
. . . f f f f . . 
. . 8 8 8 8 8 8 . 
. . a a a a a a . 
. . a a a f a f . 
. . a a a a a a . 
. . . a a a a a . 
. . . . a a a . . 
. a a 1 a a 1 a . 
a a a 1 f f 1 a a 
a a 1 f f f f 1 a 
a a f f 1 2 f f a 
a a f f 8 1 f f a 
a a f f f f f f a 
a a f f f f f f a 
a a 1 1 1 1 1 1 a 
a a f f f 8 f f a 
a a f f f 8 f f a 
. . f f f 8 f f . 
. . a a . . a a . 
. . a a . . a a . 
. . a a . . a a . 
. . 2 1 . . 2 1 . 
. . 1 1 1 . 1 1 1 
`;
            case "image5":
            case "hotshot":return img`
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . f f f f . . 
. . f e e e e f . 
. . f e e e e e . 
. . f e e f e f . 
. . f e e e e e . 
. . . e e e e e . 
. . . . e e e . . 
. e e 1 e e 1 e . 
e e e 1 f f 1 e e 
e e 1 f f f f 1 e 
e e f f 1 2 f f e 
e e f f 8 1 f f e 
e e f f f f f f e 
e e 1 1 1 1 1 1 e 
e e f f f 8 f f e 
. . f f f 8 f f . 
. . e e . . e e . 
. . 2 1 . . 2 1 . 
. . 1 1 1 . 1 1 1 
`;
            case "image8":
            case "torch":return img`
. . f f . . . . . 
. f f f f . . . . 
. f f f f f f . . 
. f 2 2 2 2 2 2 . 
. . f f a a a a . 
. . f f a f a f . 
. . f a a a a a . 
. . . a a a a a . 
. . . . a a a . . 
. a a 1 a a 1 a . 
a a a 1 f f 1 a a 
a a 1 f f f f 1 a 
a a f f 1 2 f f a 
a a f f 8 1 f f a 
a a f f f f f f a 
a a 1 1 1 1 1 1 a 
a a f f f 8 f f a 
a a f f f 8 f f a 
. . f f f 8 f f . 
. . a a . . a a . 
. . a a . . a a . 
. . 2 1 . . 2 1 . 
. . 1 1 1 . 1 1 1 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "hotshot_shooting":
            case "anim15":return [img`
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . f f f f . . . . . 
. . f e e e e f . . . . 
. . f e e e e e . . . . 
. . f e e f e f . . . . 
. . f e e e e e . . . . 
. . . e e e e e . . . . 
. . e 1 e e 1 1 1 8 . . 
. e e f f f f 1 1 8 f . 
. e e f 1 2 2 f 1 f 1 1 
. e e f 8 f f f f f f f 
. e e e e e 1 f 1 f 2 e 
. e e e e e f 8 1 1 f e 
. . 1 1 1 1 1 8 1 1 . . 
. . f e e 8 f e e . . . 
. . e e e . e e e . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. e e . . . e e . . . . 
. e e f f f f e . . . . 
. e e f e e e f . . . . 
. e e e e e e e . . . . 
. e e e e f e f . . . . 
. e e e e e e e . . . . 
. e e e e e e e . . . . 
. e e . e e e e . . . . 
. e e 1 e e 1 e . . . . 
. e e 1 f f 1 e . . . . 
. e 1 f f f f 1 . . . . 
. . f f 1 2 f f . . . . 
. . f f 8 1 f f . . . . 
. . f f f f f f . . . . 
. . f f f f f f . . . . 
. . 1 1 1 1 1 1 . . . . 
. . f f f 8 f f . . . . 
. . f f f 8 f f . . . . 
. . e e . . e e . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . f f f f . . . . . 
. . f f e e e f . . . . 
. . f e e e e e . . . . 
. . f e e f e f . . . . 
. . f e e e e e . . . . 
. . . e e e e e . . . . 
. . . . e e e . . . . . 
. e e 1 e e 1 e . . . . 
e e e 1 f f 1 e e . . . 
e e 1 f f f f 1 e . . . 
e e f f 1 2 f f e . . . 
e e f f 8 1 f f e . . . 
e e f f f f f f e . . . 
e e 1 1 1 1 1 1 e . . . 
e e f f f 8 f f e . . . 
. . f f f 8 f f . . . . 
. . e e . . e e . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . f f f f . . . . . 
. . f f e e e f . . . . 
. . f e e e e e . . . . 
. . f e e f e f . . . . 
. . f e e e e e . . . . 
. . . e e e e e . . . . 
. . . . e e e . . . . . 
. e e 1 e e 1 e . . . . 
e e e 1 f f 1 e e . . . 
e e 1 f f f f 1 e . . . 
e e f f 1 2 f f e . . . 
e e f f 8 1 f f e . . . 
e e f f f f f f e . . . 
e e 1 1 1 1 1 1 e . . . 
e e f f f 8 f f e . . . 
. . f f f 8 f f . . . . 
. . e e . . e e . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . f f f f . . . . . 
. . f f e e e f . . . . 
. . f e e e e e . . . . 
. . f e e f e f . . . . 
. . f e e e e e . . . . 
. . . e e e e e . . . . 
. . . . e e e . . . . . 
. e e 1 e e 1 e . . . . 
e e e 1 f f 1 e e . . . 
e e 1 f f f f 1 e . . . 
e e f f 1 2 f f e . . . 
e e f f 8 1 f f e . . . 
e e f f f f f f e . . . 
e e 1 1 1 1 1 1 e . . . 
e e f f f 8 f f e . . . 
. . f f f 8 f f . . . . 
. . e e . . e e . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`];
            case "cheese_shooting":
            case "anim13":return [img`
............
............
............
............
...ffff.....
..888888....
..aaaaaa....
..aaafaf....
..aaaaaa....
...aaaaa....
....aaa.....
..a1aa1a....
.aa1ff1118..
.aaffff118..
.aaf12ff1f11
.aaf8fffffff
.aaaaa1f1f2a
.aaaaaf811fa
..11111811a.
..fff8ff....
..fff8fff...
..faa8faa...
..aaa.aaa...
..aa..aa....
..21..21....
..111.111...
`, img`
.aa...aa....
.aaffffa....
.aa88888....
.aaaaaaa....
.aaaafaf....
.aaaaaaa....
.aaaaaaa....
.aaaaaaa....
.aa.aa1a....
.aa1ff1a....
.a1ffff1....
..ff12ff....
..ff81ff....
..ffffff....
..ffffff....
..111111....
..fff8ff....
..fff8ff....
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`, img`
............
............
............
...ffff.....
..888888....
..aaaaaa....
..aaafaf....
..aaaaaa....
...aaaaa....
....aaa.....
.aa1aa1a....
aaa1ff1aa...
aa1ffff1a...
aaff12ffa...
aaff81ffa...
aaffffffa...
aaffffffa...
aa111111a...
aafff8ffa...
aafff8ffa...
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`, img`
............
............
............
...ffff.....
..888888....
..aaaaaa....
..aaafaf....
..aaaaaa....
...aaaaa....
....aaa.....
.aa1aa1a....
aaa1ff1aa...
aa1ffff1a...
aaff12ffa...
aaff81ffa...
aaffffffa...
aaffffffa...
aa111111a...
aafff8ffa...
aafff8ffa...
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`, img`
............
............
............
...ffff.....
..888888....
..aaaaaa....
..aaafaf....
..aaaaaa....
...aaaaa....
....aaa.....
.aa1aa1a....
aaa1ff1aa...
aa1ffff1a...
aaff12ffa...
aaff81ffa...
aaffffffa...
aaffffffa...
aa111111a...
aafff8ffa...
aafff8ffa...
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`];
            case "wham_shooting":
            case "anim14":return [img`
............
............
............
............
..fffff.....
..222222....
.fffffff....
.fffafaf....
.ffaaaaa....
..faaaaa....
....aff.....
..a1aa1a....
.aa1ff1118..
.aaffff118..
.aaf12ff1f11
.aaf8fffffff
.aaaaa1f1f2a
.aaaaaf811fa
..11111811a.
..fff8ff....
..fff8fff...
..faa8faa...
..aaa.aaa...
..aa..aa....
..21..21....
..111.111...
`, img`
.aa...aa....
.aaffffa....
.aa22222....
.aafffff....
.aafafaf....
.aaaaaaa....
.aaaaaaa....
.aaaaffa....
.aa.aa1a....
.aa1ff1a....
.a1ffff1....
..ff12ff....
..ff81ff....
..ffffff....
..ffffff....
..111111....
..fff8ff....
..fff8ff....
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`, img`
............
............
............
..fffff.....
..222222....
.fffffff....
.fffafaf....
.ffaaaaa....
..faaaaa....
....aaa.....
.aa1aa1a....
aaa1ff1aa...
aa1ffff1a...
aaff12ffa...
aaff81ffa...
aaffffffa...
aaffffffa...
aa111111a...
aafff8ffa...
aafff8ffa...
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`, img`
............
............
............
..fffff.....
..222222....
.fffffff....
.fffafaf....
.ffaaaaa....
..faaaaa....
....aaa.....
.aa1aa1a....
aaa1ff1aa...
aa1ffff1a...
aaff12ffa...
aaff81ffa...
aaffffffa...
aaffffffa...
aa111111a...
aafff8ffa...
aafff8ffa...
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`, img`
............
............
............
..fffff.....
..222222....
.fffffff....
.fffafaf....
.ffaaaaa....
..faaaaa....
....aaa.....
.aa1aa1a....
aaa1ff1aa...
aa1ffff1a...
aaff12ffa...
aaff81ffa...
aaffffffa...
aaffffffa...
aa111111a...
aafff8ffa...
aafff8ffa...
..fff8ff....
..aa..aa....
..aa..aa....
..aa..aa....
..21..21....
..111.111...
`];
            case "tnt_shooting":
            case "anim16":return [img`
..............
..............
..............
..............
....fffff.....
..fffffeef....
.ff.ffeeee....
.ff.feefef....
.ff.feeeee....
.ff..eeeee....
ff....eee.....
....e1ee1e....
...ee1ff1118..
...eeffff118..
...eef12ff1f11
...eef8fffffff
...eeeee1f1f2e
...eeeeef811fe
....11111811..
....fff8ff....
....fff8fff...
....fee8fee...
....eee.eee...
....ee..ee....
....21..21....
....111.111...
`, img`
...ee...ee....
...eeffffe....
..feeffeef....
.ffeefeeee....
.ffeefefef....
.ffeeeeeee....
.ffeeeeeee....
ff.eeeeeee....
...ee.ee1e....
...ee1ff1e....
...e1ffff1....
....ff12ff....
....ff81ff....
....ffffff....
....ffffff....
....111111....
....fff8ff....
....fff8ff....
....fff8ff....
....ee..ee....
....ee..ee....
....ee..ee....
....ee..ee....
....ee..ee....
....21..21....
....111.111...
`, img`
..............
..............
..............
....fffff.....
..fffffeef....
.ff.ffeeee....
.ff.feefef....
.ff.feeeee....
.ff..eeeee....
ff....eee.....
...ee1ee1e....
..eee1ff1ee...
..ee1ffff1e...
..eeff12ffe...
..eeff81ffe...
..eeffffffe...
..eeffffffe...
..ee111111e...
..eefff8ffe...
..eefff8ffe...
....fff8ff....
....ee..ee....
....ee..ee....
....ee..ee....
....21..21....
....111.111...
`, img`
..............
..............
..............
....fffff.....
..fffffeef....
.ff.ffeeee....
.ff.feefef....
.ff.feeeee....
.ff..eeeee....
ff....eee.....
...ee1ee1e....
..eee1ff1ee...
..ee1ffff1e...
..eeff12ffe...
..eeff81ffe...
..eeffffffe...
..eeffffffe...
..ee111111e...
..eefff8ffe...
..eefff8ffe...
....fff8ff....
....ee..ee....
....ee..ee....
....ee..ee....
....21..21....
....111.111...
`, img`
..............
..............
..............
....fffff.....
..fffffeef....
.ff.ffeeee....
.ff.feefef....
.ff.feeeee....
.ff..eeeee....
ff....eee.....
...ee1ee1e....
..eee1ff1ee...
..ee1ffff1e...
..eeff12ffe...
..eeff81ffe...
..eeffffffe...
..eeffffffe...
..ee111111e...
..eefff8ffe...
..eefff8ffe...
....fff8ff....
....ee..ee....
....ee..ee....
....ee..ee....
....21..21....
....111.111...
`];
            case "jet_shooting":
            case "anim17":return [img`
............
............
............
...ffff.....
..ffffff....
..111111....
..ffeeee....
..feefef....
..eeeeee....
...eeeee....
....eee.....
..e1ee1e....
.ee1ff1118..
.eeffff118..
.eef12ff1f11
.eef8fffffff
.eeeee1f1f2e
.eeeeef811fe
..11111811e.
..fff8ff....
..fff8fff...
..fee8fee...
..eee.eee...
..ee..ee....
..21..21....
..111.111...
`, img`
.eeffffe....
.eefffff....
.ee11111....
.eefeeee....
.eeeefef....
.eeeeeee....
.eeeeeee....
.eeeeeee....
.ee.ee1e....
.ee1ff1e....
.e1ffff1....
..ff12ff....
..ff81ff....
..ffffff....
..ffffff....
..111111....
..fff8ff....
..fff8ff....
..fff8ff....
..ee..ee....
..ee..ee....
..ee..ee....
..ee..ee....
..ee..ee....
..21..21....
..111.111...
`, img`
............
............
...ffff.....
..ffffff....
..111111....
..ffeeee....
..feefef....
..eeeeee....
...eeeee....
....eee.....
.ee1ee1e....
eee1ff1ee...
ee1ffff1e...
eeff12ffe...
eeff81ffe...
eeffffffe...
eeffffffe...
ee111111e...
eefff8ffe...
eefff8ffe...
..fff8ff....
..ee..ee....
..ee..ee....
..ee..ee....
..21..21....
..111.111...
`, img`
............
............
...ffff.....
..ffffff....
..111111....
..ffeeee....
..feefef....
..eeeeee....
...eeeee....
....eee.....
.ee1ee1e....
eee1ff1ee...
ee1ffff1e...
eeff12ffe...
eeff81ffe...
eeffffffe...
eeffffffe...
ee111111e...
eefff8ffe...
eefff8ffe...
..fff8ff....
..ee..ee....
..ee..ee....
..ee..ee....
..21..21....
..111.111...
`, img`
............
............
...ffff.....
..ffffff....
..111111....
..ffeeee....
..feefef....
..eeeeee....
...eeeee....
....eee.....
.ee1ee1e....
eee1ff1ee...
ee1ffff1e...
eeff12ffe...
eeff81ffe...
eeffffffe...
eeffffffe...
ee111111e...
eefff8ffe...
eefff8ffe...
..fff8ff....
..ee..ee....
..ee..ee....
..ee..ee....
..21..21....
..111.111...
`];
            case "torch_shooting":
            case "anim18":return [img`
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . f f . . . . . . . . 
. f f f f . . . . . . . 
. f f f f f f . . . . . 
. f 2 2 2 2 2 2 . . . . 
. . f f a a a a . . . . 
. . f f a f a f . . . . 
. . f a a a a a . . . . 
. . . a a a a a . . . . 
. . . . a a a . . . . . 
. . a 1 a a 1 1 1 8 . . 
. a a 1 f f f 1 1 8 f . 
. a a f 1 2 2 f 1 f 1 1 
. a a f 8 f f f f f f f 
. a a a a a 1 f 1 f 2 a 
. a a a a a f 8 1 1 f a 
. . 1 1 1 1 1 8 1 1 . . 
. . f f f 8 f f f . . . 
. . f a a 8 f a a . . . 
. . a a a . a a a . . . 
. . a a . . a a . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. . f f . . . . . . . . 
. a a f f . a a . . . . 
. a a f f f f a . . . . 
. a a 2 2 2 2 2 . . . . 
. a a f a a a a . . . . 
. a a f a f a f . . . . 
. a a a a a a a . . . . 
. a a a a a a a . . . . 
. a a . a a a a . . . . 
. a a 1 a a 1 a . . . . 
. a a 1 f f 1 a . . . . 
. a 1 f f f f 1 . . . . 
. . f f 1 2 f f . . . . 
. . f f 8 1 f f . . . . 
. . f f f f f f . . . . 
. . 1 1 1 1 1 1 . . . . 
. . f f f 8 f f . . . . 
. . f f f 8 f f . . . . 
. . f f f 8 f f . . . . 
. . a a . . a a . . . . 
. . a a . . a a . . . . 
. . a a . . a a . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. . . . . . . . . . . . 
. . f f . . . . . . . . 
. f f f f . . . . . . . 
. f f f f f f . . . . . 
. f 2 2 2 2 2 2 . . . . 
. . f f a a a a . . . . 
. . f f a f a f . . . . 
. . f a a a a a . . . . 
. . . a a a a a . . . . 
. . . . a a a . . . . . 
. a a 1 a a 1 a . . . . 
a a a 1 f f 1 a a . . . 
a a 1 f f f f 1 a . . . 
a a f f 1 2 f f a . . . 
a a f f 8 1 f f a . . . 
a a f f f f f f a . . . 
a a 1 1 1 1 1 1 a . . . 
a a f f f 8 f f a . . . 
a a f f f 8 f f a . . . 
. . f f f 8 f f . . . . 
. . a a . . a a . . . . 
. . a a . . a a . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. . . . . . . . . . . . 
. . f f . . . . . . . . 
. f f f f . . . . . . . 
. f f f f f f . . . . . 
. f 2 2 2 2 2 2 . . . . 
. . f f a a a a . . . . 
. . f f a f a f . . . . 
. . f a a a a a . . . . 
. . . a a a a a . . . . 
. . . . a a a . . . . . 
. a a 1 a a 1 a . . . . 
a a a 1 f f 1 a a . . . 
a a 1 f f f f 1 a . . . 
a a f f 1 2 f f a . . . 
a a f f 8 1 f f a . . . 
a a f f f f f f a . . . 
a a 1 1 1 1 1 1 a . . . 
a a f f f 8 f f a . . . 
a a f f f 8 f f a . . . 
. . f f f 8 f f . . . . 
. . a a . . a a . . . . 
. . a a . . a a . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`, img`
. . . . . . . . . . . . 
. . f f . . . . . . . . 
. f f f f . . . . . . . 
. f f f f f f . . . . . 
. f 2 2 2 2 2 2 . . . . 
. . f f a a a a . . . . 
. . f f a f a f . . . . 
. . f a a a a a . . . . 
. . . a a a a a . . . . 
. . . . a a a . . . . . 
. a a 1 a a 1 a . . . . 
a a a 1 f f 1 a a . . . 
a a 1 f f f f 1 a . . . 
a a f f 1 2 f f a . . . 
a a f f 8 1 f f a . . . 
a a f f f f f f a . . . 
a a 1 1 1 1 1 1 a . . . 
a a f f f 8 f f a . . . 
a a f f f 8 f f a . . . 
. . f f f 8 f f . . . . 
. . a a . . a a . . . . 
. . a a . . a a . . . . 
. . 2 1 . . 2 1 . . . . 
. . 1 1 1 . 1 1 1 . . . 
`];
            case "hotshot_dribble":
            case "anim9":return [img`
.....ffff..........
....ffeeef.........
....feeeee.........
....feefef.........
....feeeee.........
.....eeeee.........
......eee..........
...ee1ee1e.........
..eee1ff1ee........
..ee1ffff1eeee.....
..eeff12ffeeee.....
..eeff81ff.........
..eeffffff....811..
..ee111111...f811f.
..eefff8ff..11f1f22
....fff8ff..fffffff
....ee..ee..22f1f11
....21..21...f118f.
....111.111...118..
`, img`
...................
.....ffff..........
....ffeeef.........
....feeeee.........
....feefef.........
....feeeee.........
.....eeeee.........
..eee1eee..........
.eeee1ff1ee........
.ee.1f12f1ee.......
.ee.ff81ffeeee811..
.eeefffff1.eef811f.
..ee11111ff.11f1f22
....fff8fee.fffffff
...efff8fee.22f1f11
.2eeeef..ee..f118f.
111e.....e11..118..
.111.....211.......
..11.....11........
`];
            case "wham_dribble":
            case "anim8":return [img`
....fffff..........
....222222.........
...fffffff.........
...fffafaf.........
...ffaaaaa.........
....faaaaa.........
......aff..........
...aa1aa1a.........
..aaa1ff1aa........
..aa1ffff1a........
..aaff12ffa........
..aaff81ffaa.......
..aaffffffaaaa.....
..aaffffff.aaa.....
..aa111111.........
..aafff8ff.........
..aafff8ff....811..
....fff8ff...f811f.
....aa..aa..11f1f22
....aa..aa..fffffff
....aa..aa..22f1f11
....21..21...f118f.
....111.111...118..
`, img`
...................
....fffff..........
....222222.........
...fffffff.........
...fffafaf.........
...ffaaaaa.........
....faaaaa.........
......aff..........
...aa1aa1a.........
..aaa1ff1aa........
.aaa1ffff1a........
.aa.ff12ffaa.......
.aa.ff81ffaa.......
.aa.ffffff.aaa.....
..aafffff1..aa811..
..aa11111ff..f811f.
...ffff8ffa.11f1f22
...afff8faa.fffffff
..aaaff..aa.22f1f11
.2aaa....aa..f118f.
111a.....a11..118..
.111.....211.......
..11.....11........
`];
            case "tnt_dribble":
            case "anim10":return [img`
....fffff..........
..fffffeef.........
.ff.ffeeee.........
.ff.ffefef.........
.ff.feeeee.........
.ff..eeeee.........
ff....eee..........
...ee1ee1e.........
..eee1ff1ee........
..ee1ffff1e........
..eeff12ffe........
..eeff81ffee.......
..eeffffffeeee.....
..eeffffff.eee.....
..ee111111.........
..eefff8ff.........
..eefff8ff....811..
....fff8ff...f811f.
....ee..ee..11f1f22
....ee..ee..fffffff
....ee..ee..22f1f11
....21..21...f118f.
....111.111...118..
`, img`
...................
....fffff..........
..fffffeef.........
.ff.ffeeee.........
.ff.ffefef.........
.ff.feeeee.........
.ff..eeeee.........
ff....eee..........
...ee1ee1e.........
..eee1ff1ee........
.eee1ffff1e........
.ee.ff12ffee.......
.ee.ff81ffee.......
.ee.ffffff.eee.....
..eefffff1..ee811..
..ee11111ff..f811f.
...ffff8ffe.11f1f22
...efff8fee.fffffff
..eeeff..ee.22f1f11
.2eee....ee..f118f.
111e.....e11..118..
.111.....211.......
..11.....11........
`];
            case "cheese_dribble":
            case "anim7":return [img`
.....ffff..........
....888888.........
....aaaaaa.........
....aaafaf.........
....aaaaaa.........
.....aaaaa.........
......aaa..........
...aa1aa1a.........
..aaa1ff1aa........
..aa1ffff1a........
..aaff12ffa........
..aaff81ffaa.......
..aaffffffaaaa.....
..aaffffff.aaa.....
..aa111111.........
..aafff8ff.........
..aafff8ff....811..
....fff8ff...f811f.
....aa..aa..11f1f22
....aa..aa..fffffff
....aa..aa..22f1f11
....21..21...f118f.
....111.111...118..
`, img`
...................
.....ffff..........
....888888.........
....aaaaaa.........
....aaafaf.........
....aaaaaa.........
.....aaaaa.........
......aaa..........
...aa1aa1a.........
..aaa1ff1aa........
.aaa1ffff1a........
.aa.ff12ffaa.......
.aa.ff81ffaa.......
.aa.ffffff.aaa.....
..aafffff1..aa811..
..aa11111ff..f811f.
...ffff8ffa.11f1f22
...afff8faa.fffffff
..aaaff..aa.22f1f11
.2aaa....aa..f118f.
111a.....a11..118..
.111.....211.......
..11.....11........
`];
            case "torch_standing":
            case "anim6":return [img`
..ff.............
.ffff............
.ffffff..........
.f222222.........
..ffaaaa.........
..ffafaf.........
..faaaaa.........
...aaaaa.........
....aaa..........
.aa1aa1a.........
aaa1ff1aa........
aa1ffff1a........
aaff12ffaa.......
aaff81ffaa.......
aaffffff.aaa811..
aa111111..af811f.
aafff8ff..11f1f22
aafff8ff..fffffff
..fff8ff..22f1f11
..aa..aa...f118f.
..aa..aa....118..
..21..21.........
..111.111........
`, img`
..ff.............
.ffff............
.ffffff..........
.f222222.........
..ffaaaa.........
..ffafaf.........
..faaaaa.........
...aaaaa.........
....aaa..........
.aa1aa1a.........
aaa1ff1aa........
aa1ffff1a........
aaff12ffaa.......
aaff81ffaaaa.....
aaffffff.aaa.....
aa111111.........
aafff8ff....811..
aafff8ff...f811f.
..fff8ff..11f1f22
..aa..aa..fffffff
..aa..aa..22f1f11
..21..21...f118f.
..111.111...118..
`];
            case "jet_standing":
            case "anim5":return [img`
...ffff..........
..ffffff.........
..111111.........
..ffeeee.........
..feefef.........
..eeeeee.........
...eeeee.........
....eee..........
.ee1ee1e.........
eee1ff1ee........
ee1ffff1e........
eeff12ffe........
eeff81ffee.......
eeffffffee.......
eeffffff.eee.....
ee111111..ee811..
eefff8ff...f811f.
eefff8ff..11f1f22
..fff8ff..fffffff
..ee..ee..22f1f11
..ee..ee...f118f.
..ee..ee....118..
..21..21.........
..111.111........
`, img`
...ffff..........
..ffffff.........
..111111.........
..ffeeee.........
..feefef.........
..eeeeee.........
...eeeee.........
....eee..........
.ee1ee1e.........
eee1ff1ee........
ee1ffff1e........
eeff12ffe........
eeff81ffee.......
eeffffffeeee.....
eeffffff.eee.....
ee111111.........
eefff8ff.........
eefff8ff....811..
..fff8ff...f811f.
..ee..ee..11f1f22
..ee..ee..fffffff
..ee..ee..22f1f11
..21..21...f118f.
..111.111...118..
`];
            case "tnt_standing":
            case "anim4":return [img`
....fffff..........
..fffffeef.........
.ff.ffeeee.........
.ff.ffefef.........
.ff.feeeee.........
.ff..eeeee.........
ff....eee..........
...ee1ee1e.........
..eee1ff1ee........
..ee1ffff1e........
..eeff12ffe........
..eeff81ffee.......
..eeffffffee.......
..eeffffff.eee.....
..ee111111..ee811..
..eefff8ff...f811f.
..eefff8ff..11f1f22
....fff8ff..fffffff
....ee..ee..22f1f11
....ee..ee...f118f.
....ee..ee....118..
....21..21.........
....111.111........
`, img`
....fffff..........
..fffffeef.........
.ff.ffeeee.........
.ff.ffefef.........
.ff.feeeee.........
.ff..eeeee.........
ff....eee..........
...ee1ee1e.........
..eee1ff1ee........
..ee1ffff1e........
..eeff12ffe........
..eeff81ffee.......
..eeffffffeeee.....
..eeffffff.eee.....
..ee111111.........
..eefff8ff.........
..eefff8ff....811..
....fff8ff...f811f.
....ee..ee..11f1f22
....ee..ee..fffffff
....ee..ee..22f1f11
....21..21...f118f.
....111.111...118..
`];
            case "hotshot_standing":
            case "anim3":return [img`
...ffff..........
..ffeeef.........
..feeeee.........
..feefef.........
..feeeee.........
...eeeee.........
....eee..........
.ee1ee1e.........
eee1ff1ee........
ee1ffff1ee.......
eeff12ffeeee811..
eeff81ff.eef811f.
eeffffff..11f1f22
ee111111..fffffff
eefff8ff..22f1f11
..fff8ff...f118f.
..ee..ee....118..
..21..21.........
..111.111........
`, img`
...ffff..........
..ffeeef.........
..feeeee.........
..feefef.........
..feeeee.........
...eeeee.........
....eee..........
.ee1ee1e.........
eee1ff1ee........
ee1ffff1eeee.....
eeff12ffeeee.....
eeff81ff.........
eeffffff....811..
ee111111...f811f.
eefff8ff..11f1f22
..fff8ff..fffffff
..ee..ee..22f1f11
..21..21...f118f.
..111.111...118..
`];
            case "wham_standing":
            case "anim2":return [img`
..fffff..........
..222222.........
.fffffff.........
.fffafaf.........
.ffaaaaa.........
..faaaaa.........
....aff..........
.aa1aa1a.........
aaa1ff1aa........
aa1ffff1a........
aaff12ffa........
aaff81ffaa.......
aaffffffaa.......
aaffffff.aaa.....
aa111111..aa811..
aafff8ff...f811f.
aafff8ff..11f1f22
..fff8ff..fffffff
..aa..aa..22f1f11
..aa..aa...f118f.
..aa..aa....118..
..21..21.........
..111.111........
`, img`
..fffff..........
..222222.........
.fffffff.........
.fffafaf.........
.ffaaaaa.........
..faaaaa.........
....aff..........
.aa1aa1a.........
aaa1ff1aa........
aa1ffff1a........
aaff12ffa........
aaff81ffaa.......
aaffffffaaaa.....
aaffffff.aaa.....
aa111111.........
aafff8ff.........
aafff8ff....811..
..fff8ff...f811f.
..aa..aa..11f1f22
..aa..aa..fffffff
..aa..aa..22f1f11
..21..21...f118f.
..111.111...118..
`];
            case "cheese_standing":
            case "anim1":return [img`
...ffff..........
..888888.........
..aaaaaa.........
..aaafaf.........
..aaaaaa.........
...aaaaa.........
....aaa..........
.aa1aa1a.........
aaa1ff1aa........
aa1ffff1a........
aaff12ffa........
aaff81ffaa.......
aaffffffaa.......
aaffffff.aaa.....
aa111111..aa811..
aafff8ff...f811f.
aafff8ff..11f1f22
..fff8ff..fffffff
..aa..aa..22f1f11
..aa..aa...f118f.
..aa..aa....118..
..21..21.........
..111.111........
`, img`
...ffff..........
..888888.........
..aaaaaa.........
..aaafaf.........
..aaaaaa.........
...aaaaa.........
....aaa..........
.aa1aa1a.........
aaa1ff1aa........
aa1ffff1a........
aaff12ffa........
aaff81ffaa.......
aaffffffaaaa.....
aaffffff.aaa.....
aa111111.........
aafff8ff.........
aafff8ff....811..
..fff8ff...f811f.
..aa..aa..11f1f22
..aa..aa..fffffff
..aa..aa..22f1f11
..21..21...f118f.
..111.111...118..
`];
            case "torch_dribble":
            case "anim12":return [img`
....ff.............
...ffff............
...ffffff..........
...f222222.........
....ffaaaa.........
....ffafaf.........
....faaaaa.........
.....aaaaa.........
......aaa..........
...aa1aa1a.........
..aaa1ff1aa........
..aa1ffff1a........
..aaff12ffaa.......
..aaff81ffaaaa.....
..aaffffff.aaa.....
..aa111111.........
..aafff8ff....811..
..aafff8ff...f811f.
....fff8ff..11f1f22
....aa..aa..fffffff
....aa..aa..22f1f11
....21..21...f118f.
....111.111...118..
`, img`
...................
....ff.............
...ffff............
...ffffff..........
...f222222.........
....ffaaaa.........
....ffafaf.........
....faaaaa.........
.....aaaaa.........
......aaa..........
..aaa1ff1a.........
.aaaa1fff1a........
.aa.1f12ffaa.......
.aa.ff81ffaa.......
..aafffff1.aaa811..
..aa11111ff.af811f.
...ffff8ffa.11f1f22
...afff8faa.fffffff
..aaaff..aa.22f1f11
.2aaa....aa..f118f.
111a.....a11..118..
.111.....211.......
..11.....11........
`];
            case "jet_dribble":
            case "anim11":return [img`
.....ffff..........
....ffffff.........
....111111.........
....ffeeee.........
....feefef.........
....eeeeee.........
.....eeeee.........
......eee..........
...ee1ee1e.........
..eee1ff1ee........
..ee1ffff1e........
..eeff12ffe........
..eeff81ffee.......
..eeffffffeeee.....
..eeffffff.eee.....
..ee111111.........
..eefff8ff.........
..eefff8ff....811..
....fff8ff...f811f.
....ee..ee..11f1f22
....ee..ee..fffffff
....ee..ee..22f1f11
....21..21...f118f.
....111.111...118..
`, img`
...................
.....ffff..........
....ffffff.........
....111111.........
....ffeeee.........
....feefef.........
....eeeeee.........
.....eeeee.........
......eee..........
...ee1ee1e.........
..eee1ff1ee........
.eee1ffff1e........
.ee.ff12ffee.......
.ee.ff81ffee.......
.ee.ffffff.eee.....
..eefffff1..ee811..
..ee11111ff..f811f.
...ffff8ffe.11f1f22
...efff8fee.fffffff
..eeeff..ee.22f1f11
.2eee....ee..f118f.
111e.....e11..118..
.111.....211.......
..11.....11........
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
